services:

  # app:
  #   image: myapp
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgres://db:5432/mydb
  #   networks:
  #     - vaquita-network

  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: postgres
    env_file:
      - docker-env.env
    environment:
      POSTGRES_DB: vaquita
      POSTGRES_USER: vaquita_user
      POSTGRES_PASSWORD: vaquita_password
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaquita_user"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - vaquita-network

networks:
  vaquita-network:
    driver: bridge

volumes:
  db-data:


  