FROM python:3.9-slim-buster

WORKDIR /usr/src/app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 22229

ARG DATABASE_URL

ENV DATABASE_URL=$DATABASE_URL

CMD ["python", "server.py"]